CREATE TABLE rooms
(
    id         BIGINT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name       VARCHAR(255) not null,
    owner_id   BIGINT(11) UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);

ALTER TABLE rooms
    ADD CONSTRAINT fk_owner_id
        FOREIGN KEY (owner_id) REFERENCES users(id)